DROP TABLE IF EXISTS trail_tracks;

CREATE TABLE trail_tracks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    difficulity TEXT,
    track_level TEXT NOT NULL,
    track_type TEXT NOT NULL,
    img TEXT
);

