DROP TABLE IF EXISTS trail_tracks;

CREATE TABLE trail_tracks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    benefits TEXT,
    track_level TEXT NOT NULL,
    track_type TEXT NOT NULL
);

