DROP TABLE IF EXISTS trail_tracks;

CREATE TABLE trail_tracks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name_eng TEXT NOT NULL,
    alias TEXT,
    name_san TEXT NOT NULL,
    benefits TEXT,
    track_level TEXT NOT NULL,
    track_type TEXT NOT NULL,
    img TEXT,
    video TEXT NOT NULL
);

