DROP TABLE IF EXISTS track_attributes;

CREATE TABLE track_attributes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    assigned_hike_id INTEGER REFERENCES hikes(id) ON DELETE CASCADE NOT NULL,
    track_id INTEGER,
    attribute TEXT NOT NULL  
);

